info:
  title: API d'accès à comhisto selon OGC API Features
  description: |
    Cette API propose l'accès aux données de [ComHisto](https://github.com/benoitdavidfr/comhisto)
    selon le protocole [OGC API Features](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html).
    Cette version 0.x expose uniquement les collections vCom et vErat.
  contact:
    email: contact@geoapi.fr
    name: Benoit DAVID
    url: https://github.com/benoitdavidfr/comhisto
  version: '0.9'
  x-keywords:
    - comhisto
    - commune
    - entité rattachée
    - commune associée
    - commune déléguée
    - arrondissement municipal
    - découpage communal
    - France
  license:
    name: Licence ouverte Etalab
    url: https://www.etalab.gouv.fr/licence-ouverte-open-licence
  termsOfService: https://benoitdavidfr.github.io/comhisto/termsOfService.html
openapi: 3.0.2
components:
  parameters:
    f:
      description: 'The optional f parameter indicates the output format which the server shall provide as part of the response document.  The default format is GeoJSON.'
      explode: false
      in: query
      name: f
      required: false
      schema:
        default: json
        enum:
          - json
          - html
          - jsonld
        type: string
      style: form
    properties:
      description: 'The properties that should be included for each feature. The parameter value is a comma-separated list of property names.'
      explode: false
      in: query
      name: properties
      required: false
      schema:
        items:
          type: string
        type: array
      style: form
    startindex:
      description: 'The optional startindex parameter indicates the index within the result set from which the server shall begin presenting results in the response document.  The first element has an index of 0 (default).'
      explode: false
      in: query
      name: startindex
      required: false
      schema:
        default: 0
        minimum: 0
        type: integer
      style: form
  responses:
    200:
      description: 'successful operation'
    default:
      content:
        application/json:
          schema:
            $ref: 'https://raw.githubusercontent.com/opengeospatial/wps-rest-binding/master/core/openapi/schemas/exception.yaml'
      description: 'Unexpected error'
paths:
  /:
    get:
      description: 'Landing page'
      operationId: getLandingPage
      parameters:
        -
          $ref: '#/components/parameters/f'
      responses:
        200:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/LandingPage'
        400:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/InvalidParameter'
        500:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/ServerError'
      summary: 'Landing page'
      tags:
        - server
  /conformance:
    get:
      description: 'API conformance definition'
      operationId: getConformanceDeclaration
      parameters:
        -
          $ref: '#/components/parameters/f'
      responses:
        200:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/ConformanceDeclaration'
        400:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/InvalidParameter'
        500:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/ServerError'
      summary: 'API conformance definition'
      tags:
        - server
  /api:
    get:
      description: 'This document'
      operationId: getOpenapi
      parameters:
        -
          $ref: '#/components/parameters/f'
      responses:
        200:
          $ref: '#/components/responses/200'
        400:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/InvalidParameter'
        default:
          $ref: '#/components/responses/default'
      summary: 'This document'
      tags:
        - server
  '/schema/{schemaId}':
    get:
      summary: Obtenir le schema JSON en fonction de son id
      operationId: getSchema
      parameters:
        - name: schemaId
          in: path
          description: local identifier of a schema
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/Feature'
        400:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/InvalidParameter'
        404:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/NotFound'
        500:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/ServerError'
      tags:
        - server
  /collections:
    get:
      description: Collections
      operationId: getCollections
      parameters:
        - $ref: '#/components/parameters/f'
      responses:
        200:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/Collections'
        400:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/InvalidParameter'
        500:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/ServerError'
      summary: Collections
      tags:
        - server
  /collections/vCom:
    get:
      summary: Obtenir les métadonnées de la collection
      description: Version de Commune
      operationId: describeVComCollection
      parameters:
        - $ref: '#/components/parameters/f'
      responses:
        200:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/Collection'
        400:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/InvalidParameter'
        404:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/NotFound'
        500:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/ServerError'
      tags:
        - vCom
  /collections/vCom/items:
    get:
      summary: Obtenir les enregistrements de cette collection
      description: Version de Commune
      operationId: getVComFeatures
      parameters:
        - $ref: '#/components/parameters/f'
        - $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/parameters/bbox'
        - $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/parameters/limit'
        - name: properties
          description: |
            The properties that should be included for each feature. The parameter value is a comma-separated list
            of property names.
          explode: false
          in: query
          required: false
          schema:
            items:
              enum:
                - cinsee
                - statut
                - dnom
              type: string
            type: array
          style: form
        - $ref: '#/components/parameters/startindex'
        - name: cinsee
          explode: false
          in: query
          required: false
          schema:
            type: string
          style: form
        - name: statut
          explode: false
          in: query
          required: false
          schema:
            type: string
          style: form
        - name: dnom
          explode: false
          in: query
          required: false
          schema:
            type: string
          style: form
      responses:
        200:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/Features'
        400:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/InvalidParameter'
        404:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/NotFound'
        500:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/ServerError'
      tags:
        - vCom
  '/collections/vCom/items/{featureId}':
    get:
      summary: Obtenir un enregistrement en fonction de son id
      description: Version de Commune
      operationId: getVComFeature
      parameters:
        - $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/parameters/featureId'
        - $ref: '#/components/parameters/f'
      responses:
        200:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/Feature'
        400:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/InvalidParameter'
        404:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/NotFound'
        500:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/ServerError'
      tags:
        - vCom
  /collections/vErat:
    get:
      summary: Obtenir les métadonnées de la collection
      description: Version d'entité rattachée
      operationId: describeVEratCollection
      parameters:
        - $ref: '#/components/parameters/f'
      responses:
        200:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/Collection'
        400:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/InvalidParameter'
        404:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/NotFound'
        500:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/ServerError'
      tags:
        - vErat
  /collections/vErat/items:
    get:
      summary: Obtenir les enregistrements de cette collection
      description: Version d'entité rattachée
      operationId: getVEratFeatures
      parameters:
        - $ref: '#/components/parameters/f'
        - $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/parameters/bbox'
        - $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/parameters/limit'
        - name: properties
          description: 'The properties that should be included for each feature. The parameter value is a comma-separated list of property names.'
          explode: false
          in: query
          required: false
          schema:
            items:
              enum:
                - cinsee
                - statut
                - dnom
              type: string
            type: array
          style: form
        - $ref: '#/components/parameters/startindex'
        - name: cinsee
          explode: false
          in: query
          required: false
          schema:
            type: string
          style: form
        - name: statut
          explode: false
          in: query
          required: false
          schema:
            type: string
          style: form
        - name: dnom
          explode: false
          in: query
          required: false
          schema:
            type: string
          style: form
      responses:
        200:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/Features'
        400:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/InvalidParameter'
        404:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/NotFound'
        500:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/ServerError'
      tags:
        - vErat
  '/collections/vErat/items/{featureId}':
    get:
      description: Obtenir un vErat par id
      operationId: getVEratFeature
      parameters:
        - $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/parameters/featureId'
        - $ref: '#/components/parameters/f'
      responses:
        200:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/Feature'
        400:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/InvalidParameter'
        404:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/NotFound'
        500:
          $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/ServerError'
      summary: Obtenir un enregistrement en fonction de son id
      tags:
        - vErat
servers:
  - description: Service de mise à disposition de ComHisto
    url: 'https://comhisto.geoapi.fr/'
tags:
  - name: server
    description: opérations de base
    externalDocs:
      description: information
      url: 'https://github.com/benoitdavidfr/comhisto'
  - name: vCom
    description: opérations sur cette collection
  - name: vErat
    description: opérations sur cette collection
